name: Qlty

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: qlty-coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qlty:
    uses: ByronWilliamsCPA/.github/.github/workflows/python-qlty-coverage.yml@88514d9bd65030debb458cb03ab953cf44f64675  # main
    permissions:
      contents: read
      actions: read
    with:
      coverage-artifact-name: coverage-reports
      coverage-file-path: coverage.xml
      coverage-format: cobertura
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
